[server]
[server.cookies]

[server.cookies.csrf]
name = "oauth.csrf_token"
secure = true
http_only = true
same_site = "Strict"

[server.cookies.access_token]
name = "oauth.access_token"
secure = true
http_only = true
same_site = "Strict"

[server.cookies.refresh_token]
name = "oauth.refresh_token"
secure = true
http_only = true
same_site = "Strict"

[server.cookies.id_token]
name = "oauth.id_token"
secure = true
http_only = true
same_site = "Strict"

[oauth]
redirect_uri = "/"
