[server]
error_url = "/error"

[server.cookies]

[server.cookies.oauth_csrf]
name = "oauth.csrf"
secure = true
http_only = true
same_site = "Lax"

[server.cookies.oauth_pkce]
name = "oauth.pkce_verifier"
secure = true
http_only = true
same_site = "Lax"

[server.cookies.access_token]
name = "oauth.access_token"
secure = true
http_only = true
same_site = "Strict"

[server.cookies.refresh_token]
name = "oauth.refresh_token"
secure = true
http_only = true
same_site = "Strict"

[server.cookies.session]
name = "_session"
secure = true
http_only = true
same_site = "Strict"

[oauth]
redirect_uri = "/"
default_scopes = ["offline_access"]
