debug = true

[server]
host = "127.0.0.1"
port = 3000
base_url = "http://localhost:3000"
error_url = "http://localhost:3000/error"

[server.cookies]

[server.cookies.oauth_csrf]
domain = ""
secure = false
same_site = "Lax"

[server.cookies.oauth_pkce]
domain = ""
secure = false
same_site = "Lax"

[server.cookies.access_token]
domain = ""
secure = false
same_site = "Strict"

[server.cookies.refresh_token]
domain = ""
secure = false
same_site = "Strict"

[server.cookies.session]
domain = ""
secure = false
same_site = "Strict"
